#!/bin/bash
# setup.sh - Generate .env file with password hash for OpenCode Server
set -e

ENV_FILE="${ENV_FILE:-.env}"
SESSION_SECRET="${SESSION_SECRET:-}"
PASSWORD_HASH="${PASSWORD_HASH:-}"

echo "╔══════════════════════════════════════════╗"
echo "║       OpenCode Server Setup              ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
	echo "Warning: $ENV_FILE already exists."
	read -p "Overwrite? (y/N) " -n 1 -r
	echo ""
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		echo "Aborted."
		exit 1
	fi
	echo ""
fi

# Generate session secret
if [ -z "$SESSION_SECRET" ]; then
	SESSION_SECRET=$(openssl rand -hex 32)
	echo "✓ Generated SESSION_SECRET"
fi

# Prompt for password
if [ -z "$PASSWORD_HASH" ]; then
	while true; do
		echo ""
		echo "Enter a password for the web interface:"
		read -s PASSWORD
		echo ""

		if [ ${#PASSWORD} -lt 8 ]; then
			echo "✗ Password must be at least 8 characters"
			continue
		fi

		echo "Confirm password:"
		read -s PASSWORD_CONFIRM
		echo ""

		if [ "$PASSWORD" != "$PASSWORD_CONFIRM" ]; then
			echo "✗ Passwords do not match"
			continue
		fi

		break
	done

	# Check for htpasswd
	if ! command -v htpasswd &>/dev/null; then
		echo ""
		echo "Error: htpasswd not found."
		echo "Install with:"
		echo "  Ubuntu/Debian: sudo apt install apache2-utils"
		echo "  macOS: brew install httpd"
		echo "  Alpine: apk add apache2-utils"
		exit 1
	fi

	# Generate bcrypt hash with correct format for Go/Docker Compose
	# htpasswd generates $2y$, Go bcrypt expects $2a$, Docker Compose needs $$
	PASSWORD_HASH=$(echo "$PASSWORD" | htpasswd -niBC 10 "" | tr -d ':\n' | sed 's/\$2y\$/\$2a\$/; s/\$/$$/g')
	echo "✓ Generated password hash"
fi

# Prompt for session expiry
echo ""
read -p "Session expiry duration (default: 24h): " SESSION_EXPIRY
SESSION_EXPIRY="${SESSION_EXPIRY:-24h}"

# Prompt for external port
echo ""
read -p "External port (default: 4096): " EXTERNAL_PORT
EXTERNAL_PORT="${EXTERNAL_PORT:-4096}"

# Prompt for OpenCode model (optional)
echo ""
read -p "OpenCode model (default: anthropic/claude-sonnet-4-5): " OPENCODE_MODEL
OPENCODE_MODEL="${OPENCODE_MODEL:-anthropic/claude-sonnet-4-5}"

# Prompt for API key (optional)
echo ""
echo "API keys (optional - can be set later):"
read -p "Anthropic API Key (press Enter to skip): " ANTHROPIC_KEY
read -p "OpenAI API Key (press Enter to skip): " OPENAI_KEY

# Write .env file
cat >"$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -Iseconds)
# OpenCode Server Configuration

# Password hash (bcrypt, \$2a\$ format, escaped for Docker Compose)
AUTH_PASSWORD_HASH=$PASSWORD_HASH

# Session secret (random 32 bytes)
SESSION_SECRET=$SESSION_SECRET

# Session expiry duration
SESSION_EXPIRY=$SESSION_EXPIRY

# OpenCode model
OPENCODE_ARGS=--model $OPENCODE_MODEL

# External port (change in docker-compose.yml if modified)
# EXTERNAL_PORT=$EXTERNAL_PORT

# API keys (optional)
EOF

if [ -n "$ANTHROPIC_KEY" ]; then
	echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY" >>"$ENV_FILE"
fi

if [ -n "$OPENAI_KEY" ]; then
	echo "OPENAI_API_KEY=$OPENAI_KEY" >>"$ENV_FILE"
fi

# Update docker-compose.yml port if not default
if [ "$EXTERNAL_PORT" != "4096" ]; then
	if [ -f "docker-compose.yml" ]; then
		sed -i.bak "s/ports:\s*$/ports:\n      - \"$EXTERNAL_PORT:4096\"/" docker-compose.yml 2>/dev/null ||
			sed -i '' "s/ports:\s*$/ports:\n      - \"$EXTERNAL_PORT:4096\"/" docker-compose.yml 2>/dev/null ||
			echo "Note: Update docker-compose.yml ports manually to \"$EXTERNAL_PORT:4096\""
	fi
fi

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║          Setup Complete!                 ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "Created: $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Review $ENV_FILE"
if [ -n "$ANTHROPIC_KEY" ] || [ -n "$OPENAI_KEY" ]; then
	echo "  2. API keys configured"
else
	echo "  2. Add your API keys to $ENV_FILE"
fi
echo "  3. Run: docker compose up -d"
echo "  4. Access: http://localhost:$EXTERNAL_PORT"
echo "  5. Login with the password you set"
echo ""
echo "To stop: docker compose down"
echo "To view logs: docker compose logs -f"
